"""empty message

Revision ID: 3bf354c2b1d1
Revises: 32da83f444ec
Create Date: 2020-11-13 16:28:07.089448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf354c2b1d1'
down_revision = '32da83f444ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('about', sa.String(), nullable=True))
    op.add_column('games', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('imgSrc', sa.String(), nullable=True))
    op.add_column('games', sa.Column('platforms', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'platforms')
    op.drop_column('games', 'imgSrc')
    op.drop_column('games', 'genres')
    op.drop_column('games', 'created_at')
    op.drop_column('games', 'about')
    # ### end Alembic commands ###
