"""empty message

Revision ID: 3e225e6baf06
Revises: 3bf354c2b1d1
Create Date: 2020-11-13 19:08:28.310268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e225e6baf06'
down_revision = '3bf354c2b1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'updated_at')
    # ### end Alembic commands ###
