"""empty message

Revision ID: 7fbf2d3762d8
Revises: 5530bd90f12a
Create Date: 2020-11-14 04:13:26.217299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbf2d3762d8'
down_revision = '5530bd90f12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'status')
    # ### end Alembic commands ###
